<?php

/**
 * @file
 * Contains dddsvq_users.module.
 */

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Add the attendee role by default to new users.
 */
function dddsvq_sessions_user_presave(\Drupal\user\UserInterface $account) {
  if ($account->isNew()) {
    $account->addRole('attendee');
  }
}

/**
 * Implements hook_entity_view().
 */
function dddsvq_users_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode) {
  if ($entity->getEntityTypeId() == 'user' && $view_mode !== 'compact') {
    if ($entity->field_register_picture->isEmpty()) {
      $build['default_user_image'] = ['#markup' => '
      <div class="field--name-field-register-picture">
        <img src="/themes/da_vinci/images/avatar.svg">
      </div>'];
    }
  }
}
