<?php

/**
 * @file
 * Contains dddsvq_sponsors.module..
 */

/**
 * Implements hook_theme().
 */
function dddsvq_sponsors_theme($existing, $type, $theme, $path) {
  $themes = [];

  // Defines the Sponsor call to action theme.
  $themes['sponsor_call_to_action'] = [
    'variables' => [
      'text' => '',
      'link' => NULL,
    ],
  ];
  // Defines the rotation entity theme.
  $themes['rotation_entity'] = [
    'render element' => 'elements',
    'variables' => [
      'entities' => [],
      'level' => '',
    ],
  ];

  // Defines the the sponsors_wrapper theme_wrapper.
  $themes['sponsors_wrapper'] = [
    'render element' => 'element',
  ];

  // Defines a sponsor level block.
  $themes['sponsors'] = [
    'variables' => [
      'title' => '',
      'sponsor_type' => '',
      'sponsors' => [],
    ]
  ];

  return $themes;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function dddsvq_sponsors_preprocess_sponsors_wrapper(&$variables) {
  $variables['content'] = $variables['element']['#children'];
  $variables['is_front'] = \Drupal::service('path.matcher')->isFrontPage();
}
