<?php

/**
 * @file
 * Contains dddsvq_common.module
 */

/**
 * Implements hook_theme().
 */
function dddsvq_common_theme($existing, $type, $theme, $path) {
  $themes = [];

  // The newsletter theme:
  $themes['newsletter_block'] = [
    'render element' => 'element',
  ];

  $themes['date_block'] = [
    'render element' => 'element',
  ];

  $themes['copyright_block'] = [
    'render element' => 'element',
  ];

  $themes['keywords_block'] = [
    'render element' => 'element',
  ];

  $themes['social_networks'] = [
    'variables' => ['networks' => []],
  ];

  return $themes;
}

/**
 * Implements hook_entity_base_field_info_alter().
 */
function dddsvq_common_entity_base_field_info_alter(&$fields, \Drupal\Core\Entity\EntityTypeInterface $entity_type) {
  // Make created field configurable on view modes.
  if ($entity_type->id() == 'node' && !empty($fields['created'])) {
    $fields['created']->setDisplayConfigurable('view', TRUE);
  }
}
